#!/usr/bin/env python3
"""Rename a model's slug everywhere the repository writes it down.

A model's name in llm.json is its identity: every source's mapping file points
at it, the Artificial Analysis mapping is keyed by it, and update.py reads AA
directly for a model whose name *is* an AA slug (`update.resolve_aa_slugs`).
That last rule is why renaming matters rather than being cosmetic. A model added
by hand before Artificial Analysis tracked it carries whatever slug seemed right
at the time; when AA later publishes it under a different one, renaming the
entry to that slug is what connects the two, with no mapping entry to maintain.

Renaming is therefore not a one-line edit of llm.json. A name left behind in a
mapping file does not fail loudly -- it silently stops matching, and the scores
that source used to write simply stop arriving. So this module changes every
place at once, or nothing:

  * llm.json                                    the entry's own name
  * model-name-mapping-<source>-to-...json      a *value*, per MODELS route
  * model-name-mapping-llm-to-...json           a *key* (llm name -> AA slugs)
  * ...-llm-to-artificialanalysis-ignored.json  a *key* (rejected AA suggestions)
  * check_new-decisions.json                    a *key*, when one is pending

The mapping files are written through their own `add_*` writers rather than
re-serialised here, so each file keeps the shape its module gives it -- one of
them does not sort its keys, and a bulk rewrite would reorder the whole file for
a one-line change.

`_pending/pending.json` is deliberately not touched: it is regenerated by the
next collect run, and a question about the old name simply stops applying.
"""

from __future__ import annotations

import importlib
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import _new_models
import propose
from _artificialanalysis_mapping import (
    AA_MODEL_IGNORES,
    AA_MODEL_MAPPING,
    load_ignored_aa_suggestions,
    load_raw_llm_to_aa,
    write_ignored_aa_suggestions,
    write_llm_to_aa_mapping,
)
from _reference import REFERENCE_MODELS, load_reference_slugs, rename_reference_slug

HERE = Path(__file__).resolve().parent
DEFAULT_LLM_JSON = HERE / "llm.json"
JSON_DUMP_KWARGS = {"indent": 2, "ensure_ascii": False}

# The shape every name in llm.json has today: lowercase, digits, and single
# dots or dashes between them. A new name is checked against it because the
# slug ends up in URLs, in flag names and in every mapping file.
SLUG_RE = re.compile(r"^[a-z0-9]+(?:[.-][a-z0-9]+)*$")


class RenameError(Exception):
    """The rename must not go ahead. The message is shown to the caller."""


@dataclass(frozen=True)
class Change:
    """One file a rename would touch, and what it would do to it."""

    path: Path
    detail: str

    def __str__(self) -> str:
        return f"{self.path.name}: {self.detail}"


def value_routes() -> list[propose.Route]:
    """The routes whose mapping files hold llm.json model names as values.

    Read off propose.ROUTES rather than listed again, so a source added there
    is renamed with everything else instead of being quietly forgotten. The
    benchmark-label routes are excluded by their universe, and the AA route by
    running the other way round -- its keys are the model names.
    """
    seen: dict[str, propose.Route] = {}
    for by_kind in propose.ROUTES.values():
        for route in by_kind.values():
            if route.universe != propose.MODELS:
                continue
            seen.setdefault(f"{route.module}.{route.mapping_const}", route)
    return list(seen.values())


def route_path(route: propose.Route) -> Path:
    return getattr(importlib.import_module(route.module), route.mapping_const)


def touched_paths(llm_path: Path = DEFAULT_LLM_JSON) -> list[Path]:
    """Every file a rename may write, for a caller that snapshots before it."""
    paths = {
        llm_path,
        AA_MODEL_MAPPING,
        AA_MODEL_IGNORES,
        REFERENCE_MODELS,
        _new_models.DECISIONS_FILE,
        *(route_path(route) for route in value_routes()),
    }
    return sorted(paths)


def load_doc(llm_path: Path) -> dict[str, Any]:
    doc = json.loads(llm_path.read_text(encoding="utf-8"))
    if not isinstance(doc, dict) or not isinstance(doc.get("models"), list):
        raise RenameError(f"{llm_path.name} has no models array")
    return doc


def model_names(doc: dict[str, Any]) -> set[str]:
    return {m.get("name") for m in doc["models"] if isinstance(m, dict)}


def check(old: str, new: str, doc: dict[str, Any]) -> None:
    """Refuse a rename that cannot be right, before anything is read further."""
    if old == new:
        raise RenameError(f"{old!r} is already its name")
    if not SLUG_RE.fullmatch(new):
        raise RenameError(
            f"{new!r} is not a model slug: lowercase letters, digits, and single "
            "dots or dashes between them"
        )
    names = model_names(doc)
    if old not in names:
        raise RenameError(f"{old!r} is not a model in llm.json")
    if new in names:
        raise RenameError(f"{new!r} is already a model in llm.json; merge them by hand")


def plan(old: str, new: str, llm_path: Path = DEFAULT_LLM_JSON) -> list[Change]:
    """What a rename would change. Reads only -- nothing here writes."""
    doc = load_doc(llm_path)
    check(old, new, doc)

    changes = [Change(llm_path, f"model {old!r} -> {new!r}")]

    for route in value_routes():
        path = route_path(route)
        keys = [key for key, value in _string_entries(path).items() if value == old]
        if keys:
            changes.append(
                Change(path, f"{len(keys)} source name(s) now point at {new!r}: {', '.join(sorted(keys))}")
            )

    if old in load_raw_llm_to_aa(AA_MODEL_MAPPING):
        changes.append(Change(AA_MODEL_MAPPING, f"AA mapping key {old!r} -> {new!r}"))
    if old in load_ignored_aa_suggestions(AA_MODEL_IGNORES):
        changes.append(Change(AA_MODEL_IGNORES, f"rejected AA suggestions move to {new!r}"))
    if old in _new_models.load_decisions():
        changes.append(Change(_new_models.DECISIONS_FILE, f"pending decision moves to {new!r}"))
    if old in load_reference_slugs():
        changes.append(
            Change(REFERENCE_MODELS, f"reference model {old!r} -> {new!r}")
        )

    return changes


def rename(old: str, new: str, llm_path: Path = DEFAULT_LLM_JSON) -> list[str]:
    """Carry the rename out. Returns one log line per file changed.

    The caller is expected to have snapshotted `touched_paths()`: this walks
    several files, and a failure part way through leaves the model half-renamed,
    which is the state nothing else in the repository can detect.
    """
    doc = load_doc(llm_path)
    check(old, new, doc)
    log: list[str] = []

    for model in doc["models"]:
        if isinstance(model, dict) and model.get("name") == old:
            model["name"] = new
    llm_path.write_text(json.dumps(doc, **JSON_DUMP_KWARGS) + "\n", encoding="utf-8")
    log.append(f"{llm_path.name}: {old!r} -> {new!r}")

    for route in value_routes():
        path = route_path(route)
        keys = sorted(key for key, value in _string_entries(path).items() if value == old)
        if not keys:
            continue
        # Each file's own writer, so it keeps the shape its module gives it --
        # one of them does not sort its keys.
        writer = getattr(importlib.import_module(route.module), route.writer)
        for key in keys:
            writer(key, new)
        log.append(f"{path.name}: {len(keys)} name(s) repointed ({', '.join(keys)})")

    aa_mapping = load_raw_llm_to_aa(AA_MODEL_MAPPING)
    if old in aa_mapping:
        aa_mapping[new] = aa_mapping.pop(old)
        write_llm_to_aa_mapping(aa_mapping, AA_MODEL_MAPPING)
        log.append(f"{AA_MODEL_MAPPING.name}: key {old!r} -> {new!r}")

    ignored = load_ignored_aa_suggestions(AA_MODEL_IGNORES)
    if old in ignored:
        ignored[new] = ignored.pop(old) | ignored.get(new, set())
        write_ignored_aa_suggestions(ignored, AA_MODEL_IGNORES)
        log.append(f"{AA_MODEL_IGNORES.name}: key {old!r} -> {new!r}")

    decisions = _new_models.load_decisions()
    if old in decisions:
        decisions[new] = decisions.pop(old)
        _new_models.write_decisions(decisions)
        log.append(f"{_new_models.DECISIONS_FILE.name}: key {old!r} -> {new!r}")

    # The reference list is keyed by model name too, and a name left behind
    # there does not fail: the row simply stops being a reference row and
    # rejoins the ranking it is supposed to stand outside of.
    if rename_reference_slug(old, new):
        log.append(f"{REFERENCE_MODELS.name}: {old!r} -> {new!r}")

    return log


def _string_entries(path: Path) -> dict[str, str]:
    """A mapping file as plain string pairs; anything else is left alone.

    A value that is not a string cannot be a model name, and the writers below
    take one value per key, so there is nothing sensible to rewrite there.
    """
    if not path.exists():
        return {}
    raw: Any = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        return {}
    return {k: v for k, v in raw.items() if isinstance(k, str) and isinstance(v, str)}
