#!/usr/bin/env python3
"""Render the site's favicon set from icons/openbenchindex_logo.svg.

The master logo carries the "INDEX" wordmark under the C/bars/B monogram, and
that wordmark turns to mush once the icon is drawn much below ~120px. So the
small icons come from a cropped variant that drops the wordmark and zooms the
monogram to fill the square — the same split the hand-made icon set used before
this script existed. Both variants ship:

  icons/openbenchindex_mark.svg        cropped monogram; doubles as the SVG
                                       favicon and as the page's header logo
  favicon_16/32/48.png + favicon.ico   cropped monogram
  favicon_120/152/180/192/512.png      full logo, wordmark and all
  icons/openbenchindex_logo.png        full logo as a plain raster, for the
                                       README and anywhere SVG is awkward

Everything here is generated, so re-run this after touching the master logo
rather than editing the PNGs by hand:

    python3 -m pip install cairosvg pillow   # not in requirements.txt: build-only
    ./make_favicons.py
"""

from __future__ import annotations

import argparse
import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
MASTER = ROOT / "icons" / "openbenchindex_logo.svg"
MARK = ROOT / "icons" / "openbenchindex_mark.svg"
LOGO_PNG = ROOT / "icons" / "openbenchindex_logo.png"

# Size the raster logo has always been; kept so nothing pointing at it reflows.
LOGO_PNG_PX = 884

# The monogram's bounding box inside the master's 1536×1536 canvas: the pink C
# is a circle at (768, 768) r=307.75 and the B runs out to x=1223, so the ink
# spans x 460→1223, y 364→1076. Squared off around that centre with a little
# breathing room.
CROP_VIEWBOX = "412 290 860 860"

# Icons small enough that the wordmark would only add noise take the crop.
CROP_MAX_PX = 48

PNG_SIZES = (16, 32, 48, 120, 152, 180, 192, 512)

# What favicon.ico carries; the sizes Windows and older browsers ask for.
ICO_SIZES = (16, 32, 48)


def crop_variant(master_svg: str) -> str:
    """Return the master logo cropped to the monogram, wordmark removed."""
    # The wordmark is the one <g> in the file, kept whole by its comment marker
    # so this stays a single unambiguous cut.
    svg, removed = re.subn(
        r"\n  <!--\n    INDEX wordmark.*?\n  </g>\n",
        "\n",
        master_svg,
        flags=re.DOTALL,
    )
    if removed != 1:
        raise SystemExit(
            f"{MASTER.name}: expected exactly one INDEX wordmark group, found {removed}"
        )

    svg, replaced = re.subn(
        r'viewBox="0 0 1536 1536"', f'viewBox="{CROP_VIEWBOX}"', svg, count=1
    )
    if not replaced:
        raise SystemExit(f"{MASTER.name}: no viewBox to crop")

    # Keep the intrinsic size in step with the crop, so a consumer that drops
    # the file in without sizing it gets the mark's own dimensions.
    side = CROP_VIEWBOX.split()[2]
    svg = re.sub(r'width="1536"\n     height="1536"',
                 f'width="{side}"\n     height="{side}"', svg, count=1)

    # A gradient id is document-scoped, and both variants can end up inlined in
    # the same page, so keep them from colliding.
    for name in ("bg", "pink", "blue", "bWhite", "softShadow"):
        svg = svg.replace(f'id="{name}"', f'id="fav-{name}"')
        svg = svg.replace(f"url(#{name})", f"url(#fav-{name})")

    header = (
        "<!-- Generated by make_favicons.py from icons/openbenchindex_logo.svg."
        " Do not edit. -->\n"
    )
    return header + svg


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Render to memory and report what would change, without writing.",
    )
    args = parser.parse_args()

    try:
        import cairosvg
        from PIL import Image
    except ImportError as exc:  # pragma: no cover - depends on the local env
        raise SystemExit(
            f"{exc.name} is missing; run: python3 -m pip install cairosvg pillow"
        )

    master_svg = MASTER.read_text(encoding="utf-8")
    mark_svg = crop_variant(master_svg)

    written: list[str] = []

    def write(path: Path, data: bytes) -> None:
        if path.exists() and path.read_bytes() == data:
            return
        written.append(path.name)
        if not args.check:
            path.write_bytes(data)

    write(MARK, mark_svg.encode("utf-8"))

    renders: dict[int, bytes] = {}
    for size in PNG_SIZES:
        source = mark_svg if size <= CROP_MAX_PX else master_svg
        renders[size] = cairosvg.svg2png(
            bytestring=source.encode("utf-8"),
            output_width=size,
            output_height=size,
        )
        write(ROOT / f"favicon_{size}.png", renders[size])

    write(
        LOGO_PNG,
        cairosvg.svg2png(
            bytestring=master_svg.encode("utf-8"),
            output_width=LOGO_PNG_PX,
            output_height=LOGO_PNG_PX,
        ),
    )

    # Pillow writes the multi-resolution .ico from the largest frame down, so
    # hand it the crisp 48px render rather than letting it downscale from 512.
    ico = io.BytesIO()
    Image.open(io.BytesIO(renders[max(ICO_SIZES)])).save(
        ico, format="ICO", sizes=[(s, s) for s in ICO_SIZES]
    )
    write(ROOT / "favicon.ico", ico.getvalue())

    if not written:
        print("Icons are up to date.")
    elif args.check:
        print("Out of date, re-run without --check: " + ", ".join(written))
        return 1
    else:
        print("Wrote " + ", ".join(written))
    return 0


if __name__ == "__main__":
    sys.exit(main())
