#!/usr/bin/env python3
"""Render every derived form of the logo from icons/openbenchindex_logo.svg.

That master is the only file to edit by hand. Three shapes come out of it:

  full      the master as-is — dark tile, C/bars/B, "INDEX" wordmark.
            Ships as favicon_120/152/180/192/512.png and the raster
            icons/openbenchindex_logo.png.

  mark      the tile cropped square around the monogram, wordmark dropped
            because it is unreadable much below 120px. Ships as
            icons/openbenchindex_mark.svg, favicon_16/32/48.png, favicon.ico.

  flat      the monogram alone: no tile, no shadow, cropped tight to the ink,
            and with the B painted in currentColor so it takes the page's text
            colour in either theme. This is the one the site header wears, so
            it is injected straight into llm.html between its markers — an
            <img> could not follow the theme toggle.

The crops are measured off a render rather than hand-typed, so nudging the
artwork does not leave a stale bounding box behind.

    python3 -m pip install cairosvg pillow   # not in requirements.txt: build-only
    ./make_favicons.py            # rewrite whatever is stale
    ./make_favicons.py --check    # exit 1 if anything is out of date
"""

from __future__ import annotations

import argparse
import io
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
MASTER = ROOT / "icons" / "openbenchindex_logo.svg"
MARK = ROOT / "icons" / "openbenchindex_mark.svg"
LOGO_PNG = ROOT / "icons" / "openbenchindex_logo.png"
PAGE = ROOT / "llm.html"

# Size the raster logo has always been; kept so nothing pointing at it reflows.
LOGO_PNG_PX = 884

# How much of the square favicon is padding around the monogram. Enough to keep
# the B off the edge, tight enough that the mark still reads at 16px.
MARK_PADDING = 1.13

# Icons small enough that the wordmark would only add noise take the crop.
CROP_MAX_PX = 48

PNG_SIZES = (16, 32, 48, 120, 152, 180, 192, 512)

# What favicon.ico carries; the sizes Windows and older browsers ask for.
ICO_SIZES = (16, 32, 48)

# The master's canvas, and the resolution the ink is measured at.
CANVAS = 1536

GENERATED = "Generated by make_favicons.py from icons/openbenchindex_logo.svg. Do not edit."

# Where the header mark is spliced into the page.
PAGE_START = "<!-- brand-mark:start -->"
PAGE_END = "<!-- brand-mark:end -->"


def cut(svg: str, pattern: str, replacement: str = "", *, expect: int = 1) -> str:
    """re.sub that insists on finding exactly `expect` matches.

    Every edit below is keyed to something specific in the master, so a logo
    rewrite that moves the goalposts should fail loudly here rather than
    silently ship a variant with a background still in it.
    """
    out, found = re.subn(pattern, replacement, svg, flags=re.DOTALL)
    if found != expect:
        raise SystemExit(
            f"{MASTER.name}: expected {expect} match(es) for {pattern!r}, found {found}"
        )
    return out


def set_view(svg: str, view_box: str, width: float, height: float) -> str:
    """Point the SVG at a new window onto the artwork."""
    svg = cut(svg, r'viewBox="0 0 1536 1536"', f'viewBox="{view_box}"')
    # Intrinsic size follows the crop, so a consumer that drops the file in
    # without sizing it gets the artwork's own dimensions.
    return cut(
        svg,
        r'width="1536"\n     height="1536"',
        f'width="{width:g}"\n     height="{height:g}"',
    )


def namespace_ids(svg: str, prefix: str, names: tuple[str, ...]) -> str:
    """Prefix the gradient/filter ids so inlined variants cannot collide."""
    for name in names:
        svg = svg.replace(f'id="{name}"', f'id="{prefix}-{name}"')
        svg = svg.replace(f"url(#{name})", f"url(#{prefix}-{name})")
    return svg


def drop_wordmark(svg: str) -> str:
    # The wordmark is the file's one <g>, fenced by its comment.
    return cut(svg, r"\n  <!--\n    INDEX wordmark.*?\n  </g>\n", "\n")


def flat_variant(master_svg: str) -> str:
    """The monogram alone: no tile, no shadow, B in currentColor."""
    svg = drop_wordmark(master_svg)
    svg = cut(svg, r"\n  <!-- Background -->\n  <rect.*?/>\n", "\n")
    svg = cut(svg, r"\n    <!-- Very subtle dark.*?</radialGradient>\n", "\n")
    svg = cut(svg, r"\n    <!-- Main B -->\n    <linearGradient id=\"bWhite\".*?</linearGradient>\n", "\n")
    svg = cut(svg, r"\n    <!-- Reproduces the very slight.*?</filter>\n", "\n")
    svg = cut(svg, r'\n *filter="url\(#softShadow\)"', "", expect=3)
    # The one piece that has to answer to the page instead of the brand palette.
    svg = cut(svg, r'fill="url\(#bWhite\)"', 'fill="currentColor"')
    return namespace_ids(svg, "obi", ("pink", "blue"))


def mark_variant(master_svg: str, view_box: str, side: float) -> str:
    """The square tile, cropped to the monogram, for the icon set."""
    svg = set_view(drop_wordmark(master_svg), view_box, side, side)
    svg = namespace_ids(svg, "fav", ("bg", "pink", "blue", "bWhite", "softShadow"))
    return f"<!-- {GENERATED} -->\n" + svg


def ink_box(cairosvg, Image, svg: str) -> tuple[int, int, int, int]:
    """Measure the artwork's bounding box, in the master's user units.

    Rendered at the master's own canvas size, so a pixel is a user unit. The
    caller passes the flat variant: no background to fill the frame and no
    blur to bleed past the edges, so the alpha channel is exactly the ink.
    """
    png = cairosvg.svg2png(
        bytestring=svg.encode("utf-8"), output_width=CANVAS, output_height=CANVAS
    )
    box = Image.open(io.BytesIO(png)).getchannel("A").getbbox()
    if box is None:
        raise SystemExit(f"{MASTER.name}: rendered empty, nothing to crop to")
    return box


def splice_into_page(page: str, svg: str) -> str:
    """Replace the header mark between llm.html's markers."""
    start, end = page.find(PAGE_START), page.find(PAGE_END)
    if start == -1 or end == -1 or end < start:
        raise SystemExit(f"{PAGE.name}: {PAGE_START} / {PAGE_END} markers not found")

    indent = " " * (start - (page.rfind("\n", 0, start) + 1))
    body = "\n".join(
        (indent + line if line.strip() else "") for line in svg.strip().splitlines()
    )
    return (
        page[:start]
        + PAGE_START
        + f"\n{indent}<!-- {GENERATED} -->\n"
        + body
        + f"\n{indent}"
        + page[end:]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Render to memory and report what would change, without writing.",
    )
    args = parser.parse_args()

    try:
        import cairosvg
        from PIL import Image
    except ImportError as exc:  # pragma: no cover - depends on the local env
        raise SystemExit(
            f"{exc.name} is missing; run: python3 -m pip install cairosvg pillow"
        )

    master_svg = MASTER.read_text(encoding="utf-8")

    flat = flat_variant(master_svg)
    left, top, right, bottom = ink_box(cairosvg, Image, flat)
    width, height = right - left, bottom - top

    # Header mark: cropped to the ink exactly, so its box is its artwork and
    # the page can line it up against the title without guessing at padding.
    flat = set_view(flat, f"{left} {top} {width} {height}", width, height)
    flat = cut(
        flat,
        r'<svg xmlns="http://www\.w3\.org/2000/svg"',
        '<svg class="brand-mark" aria-hidden="true"\n     xmlns="http://www.w3.org/2000/svg"',
    )

    # Icon mark: squared off around the same ink, with room to breathe.
    side = round(max(width, height) * MARK_PADDING)
    square = (
        f"{round(left + width / 2 - side / 2)} {round(top + height / 2 - side / 2)} "
        f"{side} {side}"
    )
    mark_svg = mark_variant(master_svg, square, side)

    written: list[str] = []

    def write(path: Path, data: bytes) -> None:
        if path.exists() and path.read_bytes() == data:
            return
        written.append(path.name)
        if not args.check:
            path.write_bytes(data)

    write(MARK, mark_svg.encode("utf-8"))
    write(PAGE, splice_into_page(PAGE.read_text(encoding="utf-8"), flat).encode("utf-8"))

    renders: dict[int, bytes] = {}
    for size in PNG_SIZES:
        source = mark_svg if size <= CROP_MAX_PX else master_svg
        renders[size] = cairosvg.svg2png(
            bytestring=source.encode("utf-8"), output_width=size, output_height=size
        )
        write(ROOT / f"favicon_{size}.png", renders[size])

    write(
        LOGO_PNG,
        cairosvg.svg2png(
            bytestring=master_svg.encode("utf-8"),
            output_width=LOGO_PNG_PX,
            output_height=LOGO_PNG_PX,
        ),
    )

    # Pillow writes the multi-resolution .ico from the largest frame down, so
    # hand it the crisp 48px render rather than letting it downscale from 512.
    ico = io.BytesIO()
    Image.open(io.BytesIO(renders[max(ICO_SIZES)])).save(
        ico, format="ICO", sizes=[(s, s) for s in ICO_SIZES]
    )
    write(ROOT / "favicon.ico", ico.getvalue())

    if not written:
        print("Icons are up to date.")
    elif args.check:
        print("Out of date, re-run without --check: " + ", ".join(written))
        return 1
    else:
        print("Wrote " + ", ".join(written))
    return 0


if __name__ == "__main__":
    sys.exit(main())
